project:
  type: book

book:
  title: "Javascript på klientsidan"
  author: "Niklas P Andersson"
  date: "2/27/2026"
  chapters:
    - index.qmd
    - kap01-om-javascript.qmd
    - kap02-variabler.qmd
    - kap03-anropa-funktioner.qmd
    - kap04-dom-intro.qmd
    - kap05-villkor.qmd
    - kap06-loopar.qmd
    - kap07-funktioner.qmd
    - kap-oop.qmd
    - kap-arv.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



