project:
  type: book

book:
  title: "Javascript på klientsidan"
  author: "Niklas P Andersson"
  date: "2/27/2026"
  chapters:
    - index.qmd
    - part: "Del I - Grunden"
      chapters:
        - kap01-om-javascript.qmd
        - kap02-variabler.qmd
        - kap03-anropa-funktioner.qmd
        - kap04-dom-intro.qmd
        - kap05-villkor.qmd
        - kap06-stil.qmd
        - kap07-loopar.qmd
        - kap08-arrayer.qmd
        - kap09-funktioner.qmd
        - kap10-handelser.qmd
        - kap11-objekt.qmd
        - del1-sammanfattning.qmd
    - part: "Del II - Webben som plattform"
      chapters:
        - kap-dom-traversering.qmd
        - kap-skapa-element.qmd

    - part: "Del III - Javascript på djupet"
      chapters:
        - kap-moduler.qmd
        - kap-oop.qmd
        - kap-arv.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

filters:
  - filters/number-exercises.lua

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
    include-in-header: preamble.tex
    geometry:
      - paperwidth=168mm
      - paperheight=234mm
      - inner=24mm
      - outer=20mm
      - top=20mm
      - bottom=24mm



